name: prime_video_clone
description: Clon de Prime Video en Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: TituloFont
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: CuerpoFont
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: DetalleFont
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf